package:
  name: single_cell_pipeline
  version: '0.0.9'

source:
  git_url: https://amcpherson@svn.bcgsc.ca/bitbucket/scm/sc/single_cell_pipeline.git
  git_rev: v0.0.9

build:
  number: 4

requirements:
  build:
    - python

  run:
    - python
    - intervaltree
    - matplotlib
    - pypdf2
    - pypeliner
    - pysam
    - python-dateutil
    - pyvcf
    - pyyaml
    - seaborn
    - statsmodels

about:
  home: http://shahlab.ca
  summary: 'Bioinformatics pipeline for single cell analysis'

