pools:
  standard: null
  highmem: null

picard_wgs_params:
  # Minimum base quality to count a read
  min_bqual: 20

  # Minimum mapping quality to count a read
  min_mqual: 20

  # Count unpaired reads for wgs metrics
  count_unpaired: false

# HMMcopy parameters
hmmcopy_params:
  diploid:
    mu: 0,0.5,1.0,1.5,2.0,2.5,3.0

    m: 0,0.5,1.0,1.5,2.0,2.5,3.0

    kappa: 25,100,700,100,25,25,25

    e: null

    s: null

    # Optional mappability cutoff
    map_cutoff: 0.9

    # Number of states
    num_states: 7

    # Minimum mapping quality to count a read
    min_mqual: 20

    # Bin size
    bin_size: 500000

    # Binned GC content file
    gc_wig_file: /genesis/extscratch/shahlab/pipelines/reference/GRCh37-lite.gc.ws_500000.wig

    # Binned mappability file
    map_wig_file: /genesis/extscratch/shahlab/pipelines/reference/GRCh37-lite.map.ws_125_to_500000.wig

    exclude_list: /shahlab/amcpherson/projects/ith3/data/ref_db/destruct/repeats.satellite.regions


  tetraploid:
    mu: 0,0.25,0.5,0.75,1.0,1.25,1.5

    m: 0,0.25,0.5,0.75,1.0,1.25,1.5

    kappa: 25,100,700,100,25,25,25

    e: null

    s: null

    # Optional mappability cutoff
    map_cutoff: 0.9

    # Number of states
    num_states: 7

    # Minimum mapping quality to count a read
    min_mqual: 20

    # Bin size
    bin_size: 500000

    # Binned GC content file
    gc_wig_file: /genesis/extscratch/shahlab/pipelines/reference/GRCh37-lite.gc.ws_500000.wig

    # Binned mappability file
    map_wig_file: /genesis/extscratch/shahlab/pipelines/reference/GRCh37-lite.map.ws_125_to_500000.wig

    exclude_list: /shahlab/amcpherson/projects/ith3/data/ref_db/destruct/repeats.satellite.regions

  triploid:
    mu: 0,0.33,0.66,1.0,1.33,1.66,2.0

    m: 0,0.33,0.66,1.0,1.33,1.66,2.0

    kappa: 25,100,700,100,25,25,25

    e: null

    s: null

    # Optional mappability cutoff
    map_cutoff: 0.9

    # Number of states
    num_states: 7

    # Minimum mapping quality to count a read
    min_mqual: 20

    # Bin size
    bin_size: 500000

    # Binned GC content file
    gc_wig_file: /genesis/extscratch/shahlab/pipelines/reference/GRCh37-lite.gc.ws_500000.wig

    # Binned mappability file
    map_wig_file: /genesis/extscratch/shahlab/pipelines/reference/GRCh37-lite.map.ws_125_to_500000.wig

    exclude_list: /shahlab/amcpherson/projects/ith3/data/ref_db/destruct/repeats.satellite.regions


# Reference genome to align to in fasta format. Should be indexed by aligner and samtools
ref_genome: /shahlab/pipelines/reference/GRCh37-lite.fa

# Chromosomes for copy number analysis
chromosomes: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', 'X', 'Y']

mutationseq: /shahlab/pipelines/apps_centos6/mutationSeq_4.3.7_anaconda/
mutationseq_model: /shahlab/pipelines/apps_centos6/mutationSeq_4.3.7_anaconda/model_v4.1.2_anaconda_sk_0.13.1.npz

heatmap_plot_mad_threshold: 0.2

heatmap_plot_numreads_threshold: 100000

gc_windows: '/shahlab/pipelines/reference/gc_windows.txt'

one_split_job: False

memory:
  low: 2
  med: 6
  high: 18
